theme: jekyll-theme-minimal
<p align="center">
  <img src="https://github.com/SorayaEzazipour/SorayaEzazipour.github.io/blob/main/IMG_4485.JPG" width="300" title="hover text">
</p>
title: Soraya Ezazipour
Discription: PhD student in Industrial Engineering and Management
